apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-deployment
spec:
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
        - name: article
          image: ariefs/article:v1.0.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  type: LoadBalancer
  selector:
    app: article
  ports:
    - port: 8080
      targetPort: 8080
